#data_full=read.csv("C:\\Users\\Admin\\Desktop\\FILES\\COURSERA\\JHU EDA\\exdata_data_household_power_consumption.txt",header=T,, na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
getwd()
setwd("C:\\Users\\Admin\\Desktop\\FILES\\COURSERA\\JHU EDA")
data_full=read.csv("C:\\Users\\Admin\\Desktop\\FILES\\COURSERA\\JHU EDA\\household_power_consumption.txt",header=T, sep=';', na.strings="?", 
                   nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
head(data_full,10)
data_full$Date=as.Date(data_full$Date, format="%d/%m/%Y")
data=subset(data_full, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
data$Global_active_power=as.numeric(data$Global_active_power)
head(data,10)
#rm(data)
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- as.POSIXct(datetime)
plot(data$Global_active_power~data$Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()